# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6168afcdaf45271d5865b5fe913a3db327952d528499b330ccb1f45a12d48e0b943a5340a679fe1c548e0d59c702fb5cac7e47600de8c746e5a32d1884b74987

test:
  secret_key_base: dbe67da20b6bd413ba2e2736b4a3e4fc93366d9f5657ae0c029cdd7fb56fedb6f63b9f354a36389a10cb4ac937ab765ed7f2ffb6c80f8d7837756d6b51c0401e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
